language: python

python:
  - "2.7"
  - "3.6"

sudo: false

before_install:
  - export BOTO_CONFIG=/dev/null

install:
  - make setup
  - pip install coveralls

cache:
  directories:
  - $HOME/.cache/pip

script:
  - make test

after_success:
  - coveralls
